[package]
name = "firestarter"
version = "0.1.2"
authors = ["Yutaka Matsubara <yutaka.matsubara@gmail.com>"]
description = "A process and shared socket manager"
keywords = ["socket", "process-manager", "systemd", "socketactivation"]
homepage = "https://github.com/mopemope/firestarter"
repository = "https://github.com/mopemope/firestarter"
readme = "README.md"
license = "MIT/Apache-2.0"
exclude = ["demo"]

[dependencies]
clap = "2.31"
failure = "0.1"
failure_derive = "0.1"
regex = "1.0.0"
lazy_static = "1.0.0"
log = "0.4"
env_logger = "0.5"
console = "0.6"
libc = "0.2"
toml = "0.4"
mio = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
nix = "0.11.0"
chrono = "0.4"